### ISSUE TITLE
Unable to run the sample project with the given steps

### ISSUE THREAD

**Issue by ravindrasubedi** [ContextMapper/context-map-discovery#13]
I have followed the steps to run the given example.
However I am getting below error :

15:03:03.939 [main] WARN  org.reflections.Reflections - given scan urls are empty. set urls in the configuration
Exception in thread "main" java.lang.IllegalArgumentException: The Context Map must at least contain one Bounded Context to be serialized!
	at org.contextmapper.discovery.ContextMapSerializer.serializeContextMap(ContextMapSerializer.java:42)
	at com.tcs.isn.LakesideMutualContextMapDiscoverer.main(LakesideMutualContextMapDiscoverer.java:48)

**Comment by stefan-ka** [comment]
Hi @ravindrasubedi 

Have you removed the _spring-boot-maven-plugin_ plugin from the POM's before you installed the backends to your local maven repository as [described in the note in step 2](https://github.com/ContextMapper/context-map-discovery/tree/master/Examples/LakesideMutual#procedure-to-run-this-example)?

I know this is an ugly workaround. But the reflections library does not find the classes for Spring Boot JARs automatically because of the BOOT-INF folder.

Also maybe try it with the new release 1.4.0 (I updated the reflections library). However, the workaround above is still needed.

Best regards,
Stefan

**Comment by ravindrasubedi** [comment]
Hi @stefan-ka 

Yes, I had already tried removing 'spring-boot-maven-plugin' from the pom.xml files.
No luck even after upgrading to 1.4.0.

Regards,
Ravindra

**Comment by ravindrasubedi** [comment]
@stefan-ka I am using JDK 1.8

**Comment by stefan-ka** [comment]
@ravindrasubedi 
Okay, I'm on Java 11 now. Does it have to be Java 8? :)

**Comment by j-ruch** [comment]
Dear @stefan-ka 

I would like to follow up on this open issue. I'm currently working on LakesideMutual and wanted to try out the discovery function of your Context Mapper. I followed the detailed steps in your README but the discovery function is failing, but with a different error message than @ravindrasubedi experienced. 

My system: 
- MS Surface, Windows 11
- Intellij IDEA
- Oracle OpenJDK 21.0.2 and graalvm-jdk-21.0.2+13.1
- Maven 3.9.4
- Gradle 8.10

My Procedure: 
I cloned the LakesideMutual project and this context-mapper-discovery project. 
I tried to build it with gradle but it did not build correctly on my machine, I received the following issue: 

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'context-map-discovery'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.ajoberstar.grgit:grgit-core:3.1.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/3.1.1/grgit-core-3.1.1.pom
     Required by:
         root project : > nebula.release:nebula.release.gradle.plugin:13.0.0 > com.netflix.nebula:nebula-release-plugin:13.0.0

* Try:
> If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 7s`

Now I'm by no means an expert in gradle, I tried to resolve the following issue by adding an additional repository to your gradle build file according to the official gradle central websites:
https://docs.gradle.org/current/userguide/declaring_repositories.html
https://plugins.gradle.org/plugin/org.ajoberstar.grgit/3.1.1

The resulting code snippet from the gradle file is: 

`repositories {
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
}`

Now the issue kept coming up, that is why I turned to an extra maven project. 
I attach you both files such that you can see what I have configured. You will have to rename them to .java and .xml on your machine. 

The resulting Java class:
[ExampleContextMapDiscoverer.txt](https://github.com/user-attachments/files/16768292/ExampleContextMapDiscoverer.txt)

The resulting pom file:
[pom.txt](https://github.com/user-attachments/files/16768308/pom.txt)

I removed the Spring Boot Maven Plugin from each backend project and build them all with `mvn clean install` and then executed the ExampleContextMapDiscoverer main class above. 
The stacktrace which I receive when running this setup is in this file: 
[stacktrace.txt](https://github.com/user-attachments/files/16768350/stacktrace.txt)

The stacktrace mentions that multiple slf4j bindings were found, I have removed to URLs because they contain paths from my personal machine. The question arises, might these bindings be the problem? 

In case you need further details feel free to contact me. 
Thanks a lot and kind regards
Jan

**Comment by stefan-ka** [comment]
Hi @j-ruch 

Should be fixed now ;) Could you check whether it works for you as well? The problem were just some outdated dependencies in the Gradle build; we haven't touched the project for a while.

Best regards,
Stefan

**Comment by j-ruch** [comment]
Hi @stefan-ka thanks a lot for the quick support! 
I still have some problems, but maybe these occur due to my setup or missing knowhow with gradle... 

I performed the following actions: 

1. Pull the latest changes 
2. Build the main context-map-discovery project with OpenJDK 20 and Gradle 8.10 --> `Success`
3. Build the inner LakesideMutual Example project with OpenJDK 11 and Gradle 5.2.1 --> `Failure`

The file 'gradle-wrapper.properties' in the inner LakesideMutual Example project contains the following line: 

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.2.1-all.zip`

IntelliJ automatically installed the correct, pre-defined JDK via built-in Amazon Corretto JDK. The build worked out fine. But I received the following error while executing the main class 'LakesideMutualContextMapDiscoverer' 

![image](https://github.com/user-attachments/assets/3548b58a-d25e-4f1d-84ef-af095dc2b720)

I assumed that there might be a problem with the built-in JDK 11 and switched to OpenJDK 20 back again. I had to update Gradle to 8.10. I saw that you changed the ''gradle-wrapper.properties in the outer project. Thus I changed it to the latest gradle release in the inner 'gradle-wrapper.properties': 

`distributionUrl=https\://services.gradle.org/distributions/gradle-8.10-all.zip`

This update led to a new issue (see stacktrace attachement): 

[stacktrace.txt](https://github.com/user-attachments/files/16795673/stacktrace.txt)

I had to update the 'gradle.build' file to use a new specification for the JDK and remove the force attribute for the mime pull dependency. (see file attachement with the new build file, change the file ending to .gradle again)

[build.txt](https://github.com/user-attachments/files/16795809/build.txt)

Then the build worked with a JDK20 and Gradle 8.10. 
But when starting the main class 'LakesideMutualContextMapDiscoverer' I received the following exception: 

[exception.txt](https://github.com/user-attachments/files/16795880/exception.txt)

**Comment by stefan-ka** [comment]
Hi @j-ruch 

Sorry, I totally forgot about the LakesideMutual example. I updated Gradle now and for me, at least with Java 11, it seams to work again. The main() still fails with some formatting exceptions but at least it produces a CML-file. Sorry, thats what I can do today... There are still issues to be solved for newer Java versions and with the CML formatting. But maybe you can also generate a CML file now?

Best regards,
Stefan

**Comment by j-ruch** [comment]
Hi @stefan-ka 
It worked just like you explained, I also receive the CML files and an issue in the console. 
I guess you could close this issue...

It would be great if you would find the time to fix the setup entirely somewhen. In case you need any further help, you can send me a message to verify it on my end.
Thanks again for the great support, big thumbs up 👍
